RENDER = prman
FILE = straw
SLCOMPILER = oslc
VIEWER = sho
SLEXT = oso

SHADERNAME_COLOUR = outsideColor
SHADERNAME_DISPLACEMENT = strawDisplacement

SHADERNAME_COLOUR_INSIDE = insideColor
SHADERNAME_DISPLACEMENT_INSIDE = insideDisplacement

SHADERNAME_COLOUR_CAP = capColor
SHADERNAME_DISPLACEMENT_CAP = capDisplacement

SHADERNAME_WOOD = wood


all: ${FILE}.exr
	${VIEWER} ${FILE}.exr

${SHADERNAME_COLOUR}.${SLEXT}: ${SHADERNAME_COLOUR}.osl
	${SLCOMPILER} ${SHADERNAME_COLOUR}.osl

${SHADERNAME_COLOUR_INSIDE}.${SLEXT}: ${SHADERNAME_COLOUR_INSIDE}.osl
	${SLCOMPILER} ${SHADERNAME_COLOUR_INSIDE}.osl

${SHADERNAME_DISPLACEMENT_INSIDE}.${SLEXT}: ${SHADERNAME_DISPLACEMENT_INSIDE}.osl
	${SLCOMPILER} ${SHADERNAME_DISPLACEMENT_INSIDE}.osl

${SHADERNAME_COLOUR_CAP}.${SLEXT}: ${SHADERNAME_COLOUR_CAP}.osl
	${SLCOMPILER} ${SHADERNAME_COLOUR_CAP}.osl

${SHADERNAME_DISPLACEMENT_CAP}.${SLEXT}: ${SHADERNAME_DISPLACEMENT_CAP}.osl
	${SLCOMPILER} ${SHADERNAME_DISPLACEMENT_CAP}.osl

${SHADERNAME_DISPLACEMENT}.${SLEXT}: ${SHADERNAME_DISPLACEMENT}.osl
	${SLCOMPILER} ${SHADERNAME_DISPLACEMENT}.osl

${SHADERNAME_WOOD}.${SLEXT}: ${SHADERNAME_WOOD}.osl
	${SLCOMPILER} ${SHADERNAME_WOOD}.osl


${FILE}.exr: ${SHADERNAME_COLOUR}.${SLEXT} ${SHADERNAME_COLOUR_INSIDE}.${SLEXT} ${SHADERNAME_DISPLACEMENT}.${SLEXT} ${FILE}.rib ${SHADERNAME_COLOUR_CAP}.${SLEXT} ${SHADERNAME_DISPLACEMENT_CAP}.${SLEXT} ${SHADERNAME_DISPLACEMENT_INSIDE}.${SLEXT} ${SHADERNAME_WOOD}.${SLEXT}
	${RENDER} ${FILE}.rib

clean:
	rm -f *.exr *.${SLEXT}
