RENDER = prman
FILE = straw
SLCOMPILER = oslc
VIEWER = sho
SLEXT = oso

SHADERNAME_COLOUR = color
SHADERNAME_DISPLACEMENT = strawDisplacement

all: ${FILE}.exr
	${VIEWER} ${FILE}.exr

${SHADERNAME_COLOUR}.${SLEXT}: ${SHADERNAME_COLOUR}.osl
	${SLCOMPILER} ${SHADERNAME_COLOUR}.osl

${SHADERNAME_DISPLACEMENT}.${SLEXT}: ${SHADERNAME_DISPLACEMENT}.osl
	${SLCOMPILER} ${SHADERNAME_DISPLACEMENT}.osl

${FILE}.exr: ${SHADERNAME_COLOUR}.${SLEXT} ${SHADERNAME_DISPLACEMENT}.${SLEXT} ${FILE}.rib
	${RENDER} ${FILE}.rib

clean:
	rm -f *.exr *.${SLEXT}
